// AD9744 DDS output demo for ALIENTEK Navigator ZYNQ.
//
// Purpose:
//   Generate a fixed 1 kHz sine wave for the external AD9744 14-bit DAC module.
//
// Hardware notes:
//   The AD9744 module uses a 2x10 P1 header:
//     PD/CLK, D14/D13, D12/D11, ..., D2/D1, GND/GND, +5V/+5V
//   The Navigator ZYNQ baseboard does not provide a same-pinout 2x10 socket.
//   Do not plug the DAC module directly into the RGB LCD 40-pin socket unless
//   you have verified a proper adapter, because +5V/GND do not line up.
//
// Vivado/IP notes:
//   No external IP is required. Sine samples are generated by a small function,
//   and the amplitude multiplier is inferred as DSP logic by Vivado.

module ad9744_dds_top #(
    parameter integer CLK_FREQ_HZ = 50_000_000,
    parameter integer OUT_FREQ_HZ = 1_000,
    parameter integer AMPLITUDE    = 13'd4095
)(
    input  wire        sys_clk,
    input  wire        sys_rst_n,

    output wire        dac_clk,
    output wire [13:0] dac_data,
    output wire        dac_sleep,
    output wire        led0
);

    localparam [47:0] PHASE_INC =
        ((64'd281_474_976_710_656 / CLK_FREQ_HZ) * OUT_FREQ_HZ);

    reg [47:0] phase_acc;
    reg [13:0] wave_offset_binary;
    reg signed [14:0] wave_signed;
    reg signed [28:0] scaled_signed;
    reg [13:0] dac_data_r;

    wire [7:0] phase_index = phase_acc[47:40];
    wire [13:0] sine_sample = sine_lut_256(phase_index);
    wire dac_clk_forwarded;

    always @(posedge sys_clk or negedge sys_rst_n) begin
        if (!sys_rst_n) begin
            phase_acc          <= 48'd0;
            wave_offset_binary <= 14'd8192;
            wave_signed        <= 15'sd0;
            scaled_signed      <= 29'sd0;
            dac_data_r         <= 14'd8192;
        end else begin
            phase_acc          <= phase_acc + PHASE_INC;
            wave_offset_binary <= sine_sample;
            wave_signed        <= $signed({1'b0, sine_sample}) - 15'sd8192;
            scaled_signed      <= wave_signed * $signed({1'b0, AMPLITUDE});
            dac_data_r         <= 14'd8192 + scaled_signed[25:13];
        end
    end

    ODDR #(
        .DDR_CLK_EDGE("SAME_EDGE"),
        .INIT(1'b0),
        .SRTYPE("SYNC")
    ) u_dac_clk_oddr (
        .Q(dac_clk_forwarded),
        .C(sys_clk),
        .CE(1'b1),
        .D1(1'b0),
        .D2(1'b1),
        .R(1'b0),
        .S(1'b0)
    );

    assign dac_clk   = dac_clk_forwarded;
    assign dac_data  = dac_data_r;
    assign dac_sleep = 1'b0;
    assign led0      = 1'b1;

    function [13:0] sine_lut_256;
        input [7:0] addr;
        reg [7:0] qaddr;
        reg [13:0] mag;
        begin
            case (addr[7:6])
                2'b00: qaddr = addr[5:0];
                2'b01: qaddr = 8'd63 - addr[5:0];
                2'b10: qaddr = addr[5:0];
                default: qaddr = 8'd63 - addr[5:0];
            endcase

            case (qaddr[5:0])
                6'd0:  mag = 14'd0;
                6'd1:  mag = 14'd201;
                6'd2:  mag = 14'd402;
                6'd3:  mag = 14'd603;
                6'd4:  mag = 14'd803;
                6'd5:  mag = 14'd1003;
                6'd6:  mag = 14'd1202;
                6'd7:  mag = 14'd1400;
                6'd8:  mag = 14'd1598;
                6'd9:  mag = 14'd1795;
                6'd10: mag = 14'd1990;
                6'd11: mag = 14'd2185;
                6'd12: mag = 14'd2378;
                6'd13: mag = 14'd2569;
                6'd14: mag = 14'd2759;
                6'd15: mag = 14'd2948;
                6'd16: mag = 14'd3135;
                6'd17: mag = 14'd3319;
                6'd18: mag = 14'd3502;
                6'd19: mag = 14'd3683;
                6'd20: mag = 14'd3861;
                6'd21: mag = 14'd4037;
                6'd22: mag = 14'd4211;
                6'd23: mag = 14'd4382;
                6'd24: mag = 14'd4551;
                6'd25: mag = 14'd4716;
                6'd26: mag = 14'd4879;
                6'd27: mag = 14'd5039;
                6'd28: mag = 14'd5196;
                6'd29: mag = 14'd5350;
                6'd30: mag = 14'd5501;
                6'd31: mag = 14'd5648;
                6'd32: mag = 14'd5792;
                6'd33: mag = 14'd5932;
                6'd34: mag = 14'd6069;
                6'd35: mag = 14'd6202;
                6'd36: mag = 14'd6332;
                6'd37: mag = 14'd6457;
                6'd38: mag = 14'd6579;
                6'd39: mag = 14'd6697;
                6'd40: mag = 14'd6811;
                6'd41: mag = 14'd6920;
                6'd42: mag = 14'd7026;
                6'd43: mag = 14'd7127;
                6'd44: mag = 14'd7224;
                6'd45: mag = 14'd7316;
                6'd46: mag = 14'd7405;
                6'd47: mag = 14'd7488;
                6'd48: mag = 14'd7567;
                6'd49: mag = 14'd7642;
                6'd50: mag = 14'd7712;
                6'd51: mag = 14'd7778;
                6'd52: mag = 14'd7838;
                6'd53: mag = 14'd7894;
                6'd54: mag = 14'd7946;
                6'd55: mag = 14'd7992;
                6'd56: mag = 14'd8034;
                6'd57: mag = 14'd8070;
                6'd58: mag = 14'd8102;
                6'd59: mag = 14'd8129;
                6'd60: mag = 14'd8152;
                6'd61: mag = 14'd8169;
                6'd62: mag = 14'd8181;
                default: mag = 14'd8189;
            endcase

            if (addr[7])
                sine_lut_256 = 14'd8192 - mag;
            else
                sine_lut_256 = 14'd8192 + mag;
        end
    endfunction

endmodule
